### ISSUE TITLE
zMerge doesn't verify the contents of the merge data folder are safe for deletion prior to deleting them

### ISSUE THREAD

**Issue by stripe1000** [matortheeternal/zedit#179] opened 2020-04-25 16:00 UTC
Using MO2 in portable mode and giving Zedit it's own profile.  Used the clean option for Zmerge.  recieved error for failed to find masters.  However the program completely locked up and had to be hard stopped with "end task" via task manager.  After this my mods directory was left with only 4 mods folders still present.  It removed mods it was not even tasked with merging.  Not sure why the 4 folders were left or why the others were deleted but confirmed they were completely removed from my HDD, not placed in the recycling bin either.  Attaching log files in the hope this can be figured out because this is a big issue.  If this is a user error please add a warning to the documentation as I can find nothing about this issue there.
[main_2020_04_25_11_31.txt](https://github.com/z-edit/zedit/files/4533430/main_2020_04_25_11_31.txt)
[merge_2020_04_25_11_38.txt](https://github.com/z-edit/zedit/files/4533431/merge_2020_04_25_11_38.txt)
[app_2020_04_25_11_31.txt](https://github.com/z-edit/zedit/files/4533432/app_2020_04_25_11_31.txt)

**Comment by AfroScrolls** [comment] 2020-05-09 22:49
Same issue here. Just destroyed my 1067 modlist

**Comment by matortheeternal** [comment] 2020-05-19 19:35
Are you saying ESP files were deleted, or mod folders were deleted?  The code that executes there touches ESP files but not mod folders.

There is code in the xEdit codebase which can delete plugin files if the `fsIsTemporary` flag is set.  This code should never be executed by XEditLib (the DLL wrapper for xEdit codebase which zEdit uses).  I just verified that it cannot be executed by the codepath shown in your logs.  I will delete this code in a future release to be safe just in case.

It's possible that the exception caused a codepath to be followed that isn't obvious to me.  I don't know why the xEdit codebase has code for deleting plugins in it, it's rather stupid.

**Comment by stripe1000** [comment] 2020-05-19 22:39
In my case it was the actual mod folders and all the contents.  I really wish I knew how a simple program crash could cause that but I have no earthly clue.  I have seen file corruption and in come extreme cases even file deletion from programs that do not make a copy to work on while modifying a file and then copying over the original when the edits are complete but I have never seen whole directory folders deleted this way before or even have a clue how something like this might happen.  Sorry I can not be of more help.  Maybe AfroScrolls will have some additional log files and insight.

**Comment by matortheeternal** [comment] 2020-05-20 05:18
So it's basically impossible for zMerge to have deleted the folders in that case, because there isn't any code which was executing (according to your log) which was even touching those folders.  If there's a bug it would have to be with something else on your system or MO2.

**Comment by AfroScrolls** [comment] 2020-05-20 09:35
Everything in my mods folder was deleted. Esps and folders. It was a
similar issue for me where it crashed bad I closed it with task manager
because it had taken so long. I was doing a lot of different things on my
computer at once so I feel like that helped mitigate the crash. Just woke
up but will have a look for my logs ASAP. Thank you so much for all the
work you've done for the modding community! I use your programs basically
everyday.

**Comment by stripe1000** [comment] 2020-05-20 15:37
I also appreciate all the work you do for the community.  Please don't read me wrong.  I had a thought, is it possible that the esps were "open within" the folders and maybe that had something to do with this?  I am just grasping at straws but I was only doing this operation at the time.  The only other programs running were MO2 and a browser window with some instructions open.  So unless there is a compatibility issue with MO2 going on to cause this issue then I am out of ideas.

**Comment by AfroScrolls** [comment] 2020-05-20 15:55
Sorry I had a busy day but just found my logs. Think it may have something to do with that. I usually don't mess with mo2 while other programs are running but I do sometimes if it's taking a while which I know I probably shouldn't but it depends on what the program is doing. I'm not too sure which logs are relevant so I'm sorry for the spam but these are the logs between my last successful merge and me trying to make another and discovering that the files were gone. To be fair, I wouldn't be surprised if I did something silly and had too many things running on my computer that interacted in a way that may be difficult for you to detect so apologies for this but if it is an issue that can be avoided for anyone else than I may as well try and help. 

Apologies again, I haven't modded in a long time and had a lot of sleepless nights trying to build that ridiculous modlist before. Managed to rebuild most of it from an old backup but will definitely be backing up more often from now on lol. Thanks again.  
[merge_2020_05_09_21_32.txt](https://github.com/z-edit/zedit/files/4657896/merge_2020_05_09_21_32.txt)
[merge_2020_05_09_23_23.txt](https://github.com/z-edit/zedit/files/4657897/merge_2020_05_09_23_23.txt)
[main_2020_05_09_23_22.txt](https://github.com/z-edit/zedit/files/4657898/main_2020_05_09_23_22.txt)
[merge_2020_05_09_23_20.txt](https://github.com/z-edit/zedit/files/4657899/merge_2020_05_09_23_20.txt)
[app_2020_05_09_23_18.txt](https://github.com/z-edit/zedit/files/4657900/app_2020_05_09_23_18.txt)
[main_2020_05_09_23_18.txt](https://github.com/z-edit/zedit/files/4657901/main_2020_05_09_23_18.txt)
[main_2020_05_09_23_07.txt](https://github.com/z-edit/zedit/files/4657902/main_2020_05_09_23_07.txt)
[app_2020_05_09_23_08.txt](https://github.com/z-edit/zedit/files/4657903/app_2020_05_09_23_08.txt)
[main_2020_05_09_21_41.txt](https://github.com/z-edit/zedit/files/4657904/main_2020_05_09_21_41.txt)
[app_2020_05_09_21_41.txt](https://github.com/z-edit/zedit/files/4657905/app_2020_05_09_21_41.txt)
[app_2020_05_09_21_36.txt](https://github.com/z-edit/zedit/files/4657906/app_2020_05_09_21_36.txt)
[main_2020_05_09_21_36.txt](https://github.com/z-edit/zedit/files/4657907/main_2020_05_09_21_36.txt)
[main_2020_05_09_21_25.txt](https://github.com/z-edit/zedit/files/4657908/main_2020_05_09_21_25.txt)
[app_2020_05_09_21_25.txt](https://github.com/z-edit/zedit/files/4657909/app_2020_05_09_21_25.txt)

**Comment by matortheeternal** [comment] 2020-05-21 08:06
ok, I will look into this again given both of your logs show the error message three times, which is kind of weird to me.

**Comment by matortheeternal** [comment] 2020-07-06 04:31
I found the source of this issue after seeing it first-hand and doing some very close looking at logs.  The cause is having your merge destination directory set to the mod organizer mods folder (or the folder above it) and then setting the merge name to that of a folder that contains files.  The program clears the merge folder before building the merge so you don't have weird issues with leftover assets when rebuilding a merge.  To address this I've added a check which makes certain the folder being cleared was used for the merge in question.  If it wasn't and there are files/folders in it, the program will throw an error informing the user to either change the merge's name or clear the folder.

**Comment by AfroScrolls** [comment] 2020-07-06 06:11
Thank you! I'll remember that and make sure to do that in future! I knew it
would be something silly that I'd done. Thanks again for making your
program idiot proof! 😂

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by matortheeternal** [comment] 2021-09-26 15:32
was fixed in v0.6.6.1

**Closed as completed by matortheeternal** 2021-09-26 15:32 UTC
Labels: investigating
