### ISSUE TITLE
Plugin list taken from wrong place.

### ISSUE THREAD

**Issue by ForisTale** [matortheeternal/zedit#92] opened 2018-12-13 23:39 UTC
Hi. I have SkyrimVR and use MO2, but plugin list is taken from \AppData\Local\Skyrim Special Edition instead from SVR. This make me copy plugin list to SSE forder before I run zEdit/zMerge if I want correct plugin list.

**Comment by matortheeternal** [comment] 2019-04-03 18:10
Duplicate of #95.

**Closed as completed by matortheeternal** 2019-04-03 18:10 UTC
Labels: duplicate

**Comment by ForisTale** [comment] 2019-04-03 18:13
You know my post was first so #95 is duplicate of mine not other way.

**Comment by matortheeternal** [comment] 2019-04-03 18:17
OK, #95 was put together a bit better so I preferred to keep it active instead of this issue.  More importantly, SkyrimVR support is on the roadmap and will be built.  :+1:
