### ISSUE TITLE
Running Advanced Search seemingly doesn't work and then causes crash

### ISSUE THREAD

**Issue by RoboticWater** [matortheeternal/zedit#73] opened 2018-07-26 21:41 UTC
Using the Advanced Search Modal on an Mod Organizer-launched zEdit, I first applied a custom filter (conflict losers + override identical to master) to all loaded plugins (230 total), and after a long period of filtering, seemingly nothing happened. Now, this could be me misunderstanding how to use this feature (see: #72), but I was expecting to see fewer plugins with hierarchical color-coding like xEdit.

Regardless, closing the application and reopening **_not_** with Mod Organizer and only with the base Bethesda ESMs, I ran the Advanced Search again with the imported conflict losers profile. This time, however, my screen went black and I had to hard reboot my computer.

**Comment by matortheeternal** [comment] 2018-07-26 21:42
Duplicate of #56.

**Closed as completed by matortheeternal** 2018-07-26 21:42 UTC
Labels: duplicate
