### ISSUE TITLE
Handle NPC Voice Data throws error

### ISSUE THREAD

**Issue by Deztar** [matortheeternal/zedit#136] opened 2019-06-04 22:08 UTC
If I try to merge mods with Handle NPC Voice Data enabled, I get this error.
I'm on Windows 10 version 1903 build 18362.116, in case that's relevant.

```
[ERROR] Restored - Merge failed to build:
Error: Path to copy doesn't exist D:\Games\Fallout New Vegas\data\ound\voice\MainStoryAlterations.esp\creatureuniquemrhouse\VDialogueM_VDialogueMrHous_000021CC_1.ogg
    at generateNoSourceError (D:\Games\Fallout New Vegas\zEdit\resources\app.asar\node_modules\fs-jetpack\lib\copy.js:52:15)
    at checksBeforeCopyingSync (D:\Games\Fallout New Vegas\zEdit\resources\app.asar\node_modules\fs-jetpack\lib\copy.js:83:11)
    at Object.copySync [as sync] (D:\Games\Fallout New Vegas\zEdit\resources\app.asar\node_modules\fs-jetpack\lib\copy.js:150:3)
    at Object.copy (D:\Games\Fallout New Vegas\zEdit\resources\app.asar\node_modules\fs-jetpack\lib\jetpack.js:76:12)
    at copyAsset (file:///D:/Games/Fallout%20New%20Vegas/zEdit/resources/app.asar/app/app.js:8903:20)
    at entry.assets.forEach.asset (file:///D:/Games/Fallout%20New%20Vegas/zEdit/resources/app.asar/app/app.js:6093:21)
    at Array.forEach (<anonymous>)
    at merge.voiceData.forEach.entry (file:///D:/Games/Fallout%20New%20Vegas/zEdit/resources/app.asar/app/app.js:6092:30)
    at Array.forEach (<anonymous>)
    at Object.handle (file:///D:/Games/Fallout%20New%20Vegas/zEdit/resources/app.asar/app/app.js:6091:29)
```
Also, the section in Merge Edit window looks like this:

![ss (2019-06-01 at 11 25 25)](https://user-images.githubusercontent.com/9979869/58916641-edd54a80-872c-11e9-80a6-f4b84c011fe2.png)

I tried a quick and dirty fix in getVoiceDataAssets function, like this:
```let sliceLen = folder.length;```
to
```let sliceLen = folder.length - 1;```
and it works.

**Comment by matortheeternal** [comment] 2019-06-04 22:50
what is the plugin data folder for the plugin in question?  is it possible it has two trailing backslashes or some other aspect of the path which when normalized would cause the length mismatch?

**Comment by Deztar** [comment] 2019-06-04 23:43
For the particular mod in the log it is
D:\Games\Fallout New Vegas\Mod Organizer\mods\Main Story Alterations (edited)

Doesn't work with other mods too, like
D:\Games\Fallout New Vegas\Mod Organizer\mods\Legion AI-Combat bark fix

**Comment by gavincz** [comment] 2019-06-11 20:24
I can confirm this bug on Win7.
Exactly the same symptoms.
Tried and failed with:
C:\Modding\MO2\mods\Asterra's Many Fixes\Asterra's Many Fixes.esp
C:\Modding\MO2\mods\Legion AI-Combat bark fix\LegionAIFix.esp

**Comment by matortheeternal** [comment] 2019-06-11 20:34
:ok_hand: I'll see if I can get this fixed in a hotfix release.  Will verify locally and then resolve it.

**Comment by matortheeternal** [comment] 2020-03-29 20:05
OK, I finally got around to testing this.  I was unable to recreate the issue.  The problem is most likely in your profile configuration.  You may have your integrations or plugin data folders set incorrectly.

**Closed as completed by matortheeternal** 2020-03-29 20:05 UTC
Labels: bug
